### PR TITLE
Add 'Contributing' section in the README

### PR DESCRIPTION
**Pull request by douglascamata**
Adds more information for people that wish to contribute to the k8s metadata injection project.

### CODE REVIEW

**Comment by smoya** [comment]
I think Contributing sections usually goes at the end of the docs. See https://www.makeareadme.com/

**Comment by douglascamata** [comment]
There is no mention there about where the contributing section should go in https://www.makeareadme.com. I had a look at a couple of New Relic's open-source projects, and there is no standard. Also in some various open-source projects that I had a look, there seems to be no standard around this.

**Comment by smoya** [comment]
The template located at https://www.makeareadme.com/#template-1 tries to be a guideline for creating README files, so the order is respected as well.

**Comment by douglascamata** [comment]
@smoya updated 👍

**Pull request merged**
