### PR TITLE
Update the cert manager to v1.1.1 in the manifest

### PR DESCRIPTION
**Pull request by alejandrodnm**

### CODE REVIEW

**Comment by douglascamata** [comment]
Travis is 🔴

**Comment by alejandrodnm** [comment]
@douglascamata travis is red because the e2e test needs the new image version, which has not been deployed :S there is no way for this to work if I don't merge and deploy

**Comment by alejandrodnm** [comment]
@douglascamata  any suggestions? if not I'm going to merge this as I don't see a way to make the CI work if the release is not done, and this is necessary for the release.

**Comment by douglascamata** [comment]
@alejandrodnm ok... in the future, I believe the best way to run the e2e tests will be using skaffold to deploy everything 🤔 

Maybe in a future PR 😆

**Pull request merged**
